title: Conference Deadlines
description: Countdowns to target conference deadlines relevant to research for the Code World, No Blanket lab.
author: dcbrown

domain: "aideadlin.es"
baseurl: ""

github_username: code-world-no-blanket
github_repo: deadlines

markdown: kramdown
ga_id:

include: ['_pages']
